
-- Cria a tabela de locais
CREATE TABLE rental_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insere os locais únicos que já existem na tabela de locações
INSERT INTO rental_locations (name)
SELECT DISTINCT location 
FROM rentals 
WHERE location IS NOT NULL AND location != ''
ON CONFLICT (name) DO NOTHING;

-- Opcional: Se quiser garantir integridade futura (FK), mas mantendo flexibilidade por enquanto
-- ALTER TABLE rentals ADD COLUMN location_id BIGINT REFERENCES rental_locations(id);
