
-- Cria tabela de clientes
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  cpf TEXT,
  address TEXT,
  cep TEXT,
  cha_number TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Popula com dados existentes de locações (apenas nomes únicos para evitar duplicidade)
INSERT INTO clients (name, phone, cpf)
SELECT DISTINCT ON (client_name) 
    client_name, 
    client_phone, 
    client_cpf
FROM rentals
WHERE client_name IS NOT NULL AND client_name != ''
ORDER BY client_name, rental_date DESC; -- Pega o dado mais recente de cada cliente
