
-- Cria a tabela de checklists
CREATE TABLE IF NOT EXISTS checklists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  client_phone TEXT,
  jet_ski TEXT NOT NULL,
  date DATE NOT NULL,
  status_checkin TEXT DEFAULT 'Não Iniciado',
  status_checkout TEXT DEFAULT 'Não Iniciado',
  observations TEXT,
  -- Colunas JSONB permitem salvar a estrutura dos itens mesmo que incompleta
  checkin_items JSONB DEFAULT '{}'::jsonb,
  checkout_items JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilita RLS (Opcional, dependendo da sua política de segurança)
ALTER TABLE checklists ENABLE ROW LEVEL SECURITY;

-- Cria política permissiva para desenvolvimento (Ajuste conforme necessidade)
CREATE POLICY "Enable all access for all users" ON checklists FOR ALL USING (true) WITH CHECK (true);
