
-- Cria tabela para textos padrões do sistema
CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilita RLS
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Política de acesso total (leitura e escrita para todos logados)
CREATE POLICY "Enable access for all users" ON system_settings FOR ALL USING (true) WITH CHECK (true);

-- Insere o texto padrão de locação
INSERT INTO system_settings (key, value)
VALUES ('rental_contract_text', '📢 Aluguel de Jet-Ski
⛽ Combustível por conta do Locatário, sai com tanque cheio e na volta abastecido!
 📝 É obrigatório ser habilitado como MOTONAUTA.
 🚔 Não poderá ser entregue a embarcação para pessoas não habilitadas 🚔
É de responsabilidade do locatário a logística do equipamento no que se refere a: luzes da carreta rodoviária, cumprimento das leis de trânsito e segurança do bem.


Realizado contrato de locação e vistoria antes e depois!
 YAMAHA 110HP - 03 LUGARES
💰 Investimento
Diária – 🕙 das 10h às 18h – R$ 1000,00


Meia diária (manhã) – 🕙 das 10h às 14h – R$ 600,00


Meia diária (tarde) – 🕑 das 14h30 às 18h30 – R$ 600,00


Descida por conta do Locatário.


Os horários podem ser alterados conforme a disponibilidade do equipamento!
🗓️ Reservas: 📞 (48) 99634-4407 🗓️
💳 Condições de pagamento: 50% na reserva, 50% no embarque.
 Formas aceitas: Dinheiro, transferência bancária ou PIX.
 CHAVE PIX: jmsjetski@gmail.com
ATENÇÃO 📣
Descida/subida do jet pela equipe JMS será cobrado uma taxa de R$ 100,00 (Laguna-SC)


Caso não conheça o local de navegação, solicite informações.


Caso aconteça alguma pane ou alarme no painel, desligue e faça contato com nossa equipe!


Se encalhar, desligue o motor e procure ligá-lo somente depois, quando tiver uma profundidade mínima de 60 cm.


Qualquer alteração no funcionamento, desligue a máquina e solicite ajuda!


Após o horário de entrega será cobrada fração proporcional ao valor da hora de aluguel.


Passando de 30 minutos de atraso, será cobrado o valor de R$ 100,00.')
ON CONFLICT (key) DO NOTHING;
